alias i='sudo apt install'
alias i-get='sudo apt-get install'
alias upd='sudo apt update && sudo apt upgrade -y'
alias mkdir='mkdir -pv'
alias f5='source ~/.zshrc'
alias cls='clear'
alias clean='sudo apt-get autoremove && sudo apt-get autoclean && sudo apt-get clean'
# alias note='gnome-text-editor'

alias zshrc='code ~/.zshrc'
alias aliases='code ~/.bash_aliases'