add_newline = false

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[git_branch]
style = 'bold blue'
format = '[git:\(]($style)[$branch(:$remote_branch)](bold red)[\)]($style) '

[cmd_duration]
format = '[$duration](bold yellow)'

[nodejs]
disabled = true

[package]
disabled = true

[bun]
disabled = true
